import {
  capitalize,
  getLongestKey,
  matchLength,
  removeTrailingSpaces,
  stringify,
  kebabCase,
  snakeCase,
  camelCase,
  titleCase,
} from "./lib/strings.js";

export default {
  ...require("./lib/cli-utils"),
  ...require("./lib/shortcuts"),
  ...require("./lib/values"),
  capitalize,
  getLongestKey,
  matchLength,
  removeTrailingSpaces,
  stringify,
  kebabCase,
  snakeCase,
  camelCase,
  titleCase,
  ...require("./lib/encode"),
  ...require("./lib/objects"),
  ...require("./lib/revision"),
  ...require("./lib/arrays"),
  ...require("./lib/numbers"),
  ...require("./lib/store").lazyZstate,
  ...require("./lib/axios-mocks"),
  ...require("./lib/networking"),
};
